# Generated by Django 3.0.5 on 2020-09-02 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_expediente', models.IntegerField(unique=True, verbose_name='Número de expediente')),
                ('tipo_sangre', models.CharField(max_length=3, verbose_name='Tipo de sangre')),
                ('alergias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3)),
            ],
        ),
    ]
