# Generated by Django 3.0.5 on 2020-09-03 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=3),
        ),
    ]
