# Generated by Django 3.0.5 on 2020-09-03 01:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20200903_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3),
        ),
    ]
