# Generated by Django 3.0.5 on 2020-09-06 21:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import validators.paciente.json_field_schema


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200906_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(validators=[validators.paciente.json_field_schema.JSONFieldSchemaValidator(limit_value={'$id': 'http://example.com/example.json', '$schema': 'http://json-schema.org/draft-07/schema', 'additionalProperties': True, 'default': {}, 'description': 'The root schema comprises the entire JSON document.', 'examples': [{'fecha': 'Ospirin tabletas 100mg', 'medicamento': '03/09/10', 'nombre': 'Rinitivis'}], 'properties': {'fecha': {'$id': '#/properties/fecha', 'default': '', 'description': 'Valida formato de fecha.', 'examples': ['03/09/10'], 'pattern': '^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$', 'title': 'The fecha schema', 'type': 'string'}, 'medicamento': {'$id': '#/properties/medicamento', 'default': '', 'description': 'Validar nombre de medicamento y gramaje.', 'examples': ['Ospirin tabletas 100mg'], 'pattern': '^\\D*\\d(?:[,.]\\d{1,4})?\\s(tableta|g|mg|mg/ml|capsulas)$', 'title': 'The medicamento schema', 'type': 'string'}, 'nombre': {'$id': '#/properties/nombre', 'default': '', 'description': 'Validar nombre de alergia.', 'examples': ['Rinitivis'], 'pattern': '^[ a-zA-ZÀ-ÿñÑ]*$', 'title': 'The nombre schema', 'type': 'string'}}, 'required': ['nombre', 'medicamento', 'fecha'], 'title': 'The root schema', 'type': 'object'})]), size=3),
        ),
    ]
